### ISSUE TITLE
interpolateCividis yields grayscale

### ISSUE THREAD

**Issue by jrtuenge** [d3/d3-scale-chromatic#22]
When I substitute interpolateCividis for interpolateRainbow, the displayed spectrum (for my supplied log-log data) changes from purple-green to black-gray. I'm loading directly from https://d3js.org/d3-scale-chromatic.v1.min.js

**Comment by mbostock** [comment]
Works fine here:

https://observablehq.com/@d3/color-schemes?collection=@d3/d3-scale-chromatic#Cividis

Perhaps there’s an issue with how you’re loading D3 (e.g., you’re combining the d3 default bundle with an individual module such as d3-scale-chromatic)? But since you didn’t share your code, I can’t help debug.
