### ISSUE TITLE
Is this plugging compatible with d3-v3?

### ISSUE THREAD

**Issue by 1Cr18Ni9** [d3/d3-scale-chromatic#7]
Hi, Mike,
I read some demos you write putting this extension right after d3-v4.x.js,
so my question is does this extension compatible with d3-v3.x.js?
I mean does it compatible backwards.
Many Thanks!

**Comment by mbostock** [comment]
Per the [package.json](https://github.com/d3/d3-scale-chromatic/blob/v1.1.1/package.json#L33), this package depends on [d3-interpolate@1](https://github.com/d3/d3-interpolate). You could in theory load that in addition to d3@3, but depending on your environment, this could cause conflicts on the `d3` global since some of the methods in d3-interpolate@1 are the same as d3@3. You could instead use Rollup to create a custom bundle to avoid this conflict.

At any rate, I don’t support d3@3, so whatever you decide to do is up to you!
